# Generated by Django 4.1.1 on 2022-11-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='logo_color',
            field=models.CharField(default='', max_length=100),
        ),
    ]
