# Generated by Django 4.1.1 on 2022-11-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_hr', '0003_tag_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_color',
            field=models.CharField(default='', max_length=100),
        ),
    ]
