# Generated by Django 4.1.1 on 2022-11-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_hr', '0004_tag_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_color',
        ),
    ]
