# Generated by Django 4.1.2 on 2022-12-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_hr', '0005_remove_tag_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
